### ISSUE TITLE
Support for ship damage from collisions. 

### ISSUE THREAD

**Issue by austinchambers** [austinchambers/multiplayer-vr#18]
The ship needs to register damage. This issue is to handle damage from collisions, which should be a function of speed. When the ship is too badly damaged, the game ends (for now, we can just terminate input).

**Comment by damlaren** [comment]
I'm going to work on damage from collisions now, but I'll keep this open to generalize to damage from explosions & other possibilities.

**Comment by damlaren** [comment]
Added a new "BP_Health" blueprint based on ActorComponent which can be added to any Actor. This class exists to record the health of an object and provide an interface for registering damage to it. Any actor which includes a BP_Health component gains its functionality; the actor can call BP_Health->IsDestroyed to check if it is still alive during a Tick event. An example of use is on the BP_Sub class, where extra blueprint code was added to detect a collision hit and call a BP_Health function to apply damage from the collision. Currently, a sub that reaches 0 health will stop registering input but otherwise be untouched.

Later I noticed that Unreal 4 has some functions built in for applying damage, but it's not clear yet if these will be useful. They can be worked into the BP_Health class if needed.

**Comment by damlaren** [comment]
I changed the health system to use Unreal's built-in damage system. The big advantage here is that the damage system creates events (EX. a radial damage event from an explosion) that can be caught by receivers of the damage (EX. a sub near the explosion).
